# Generated by Django 4.1.7 on 2023-03-03 16:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="todo",
            name="tag",
            field=models.ManyToManyField(blank=True, to="todo.tag"),
        ),
    ]
